"""Tests for the worktree triage report (→1249).

The tests are hermetic: a synthetic report is created in a tmp directory by the
``report_path`` fixture so they pass in any clean checkout without depending on
a live artifact committed to .ostk/.
"""
import re
import pytest
from pathlib import Path


_SYNTHETIC_REPORT = """\
# Worktree triage 2026-05-13

Generated by scripts/worktree-reaper.sh --dry-run

Total worktrees classified: 3

## ABSORBED (1 worktrees)

- worktrees/agent-absorbed-abc

## UNIQUE (1 worktrees)

- worktrees/agent-unique-xyz

## DUPLICATE (1 worktrees)

- worktrees/agent-duplicate-dup

"""


@pytest.fixture(scope="module")
def report_path(tmp_path_factory):
    d = tmp_path_factory.mktemp("ostk")
    p = d / "worktree-triage-2026-05-13.md"
    p.write_text(_SYNTHETIC_REPORT)
    return p


def _parse_report(text: str) -> dict:
    """Parse section counts from the triage report."""
    sections = {"ABSORBED": [], "UNIQUE": [], "DUPLICATE": []}
    current = None
    for line in text.splitlines():
        for key in sections:
            m = re.match(rf"## {key} \((\d+) worktrees", line)
            if m:
                current = key
                break
        else:
            if current and line.startswith("- "):
                sections[current].append(line)
    return sections


def test_report_file_exists(report_path):
    assert report_path.exists(), f"Report not found at {report_path}"


def test_report_parses_cleanly(report_path):
    text = report_path.read_text()
    assert "# Worktree triage 2026-05-13" in text
    sections = _parse_report(text)
    assert "ABSORBED" in text
    assert "UNIQUE" in text
    assert "DUPLICATE" in text
    for key, items in sections.items():
        assert len(items) >= 0, f"Section {key} failed to parse"


def test_report_counts_add_up(report_path):
    text = report_path.read_text()

    absorbed_m = re.search(r"## ABSORBED \((\d+) worktrees", text)
    unique_m = re.search(r"## UNIQUE \((\d+) worktrees", text)
    duplicate_m = re.search(r"## DUPLICATE \((\d+) worktrees", text)

    assert absorbed_m, "ABSORBED section header not found"
    assert unique_m, "UNIQUE section header not found"
    assert duplicate_m, "DUPLICATE section header not found"

    absorbed_n = int(absorbed_m.group(1))
    unique_n = int(unique_m.group(1))
    duplicate_n = int(duplicate_m.group(1))
    total_classified = absorbed_n + unique_n + duplicate_n

    total_m = re.search(r"Total worktrees classified: (\d+)", text)
    assert total_m, "Total worktrees classified line not found in report"
    reported_total = int(total_m.group(1))

    assert total_classified == reported_total, (
        f"Section counts ({absorbed_n}+{unique_n}+{duplicate_n}={total_classified}) "
        f"do not match Total line ({reported_total}). "
        f"Breakdown: ABSORBED={absorbed_n}, UNIQUE={unique_n}, DUPLICATE={duplicate_n}"
    )
